### ISSUE TITLE
Resources list - link broken

### ISSUE THREAD

**Issue by pekellogg** [learn-co-curriculum/phase-0-nested-html-tags-and-attributes#5]
Hi! The first link under the Resources list (at the end of the lesson/page) leads to a 404 - not found page.

Nested Tags - http://www.bu.edu/tech/services/cccs/websites/www/non-wordpress/start/html-introduction/syntax/nesting-tags/

**Comment by graciemcguire** [comment]
Hi @pekellogg ! We have removed the broken link from the resources list! Please note that these changes will likely not be reflected in your cohorts Canvas page, just on the GitHub repository, but that they will be reflected for future students.
Thank you for flagging this, we appreciate it!
